version: '3.8'

services:
  portfolio-dev:
    build: ./app
    volumes:
      - ./app/Portfolio:/app/Portfolio
      - /app/node_modules
    container_name: portfolio-dev
    working_dir: /app/Portfolio
    command: npm run dev
    restart: unless-stopped
    environment:
      - SITE_URL=http://localhost:4000
      - NODE_ENV=development
      - PORT=3000
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent --max-time 10 --connect-timeout 2 -X POST http://192.168.27.14:11434/api/generate -H 'Content-Type: application/json' -H 'Content-Type: application/json' -d '{\"model\":\"neural-chat\",\"prompt\":\"hello\",\"stream\":false,\"keep_alive\":-1}' | grep -q 'model' || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 60s

  nginx:
    build: ./nginx
    ports:
      - "4000:80"
    environment:
      - NGINX_AUTH_USER=seshu
      - NGINX_AUTH_PASS=gnyanrocks
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dummy.crt:/etc/nginx/dummy.crt:ro
      - ./nginx/dummy.key:/etc/nginx/dummy.key:ro
      - ./videos:/usr/share/nginx/html/videos:ro # ✅ Mount the videos folder
    depends_on:
      - portfolio-dev

  load_model:
    build: ./scripts
    container_name: model_loder
    volumes:
      - ./scripts:/app/scripts
    command: ["bash", "/app/scripts/keep_alive.sh"]
    restart: unless-stopped